### ISSUE TITLE
Third Party Testing of Resgitration Page - Issues and Glitches

### ISSUE THREAD

**Issue by MichaelHallam** [Pear-Trading/Android-Terminal#1]
Responses and issues arrising out of people testing the registration page.

**Comment by MichaelHallam** [comment]
Tom at GOLFE tested the page and found a glitch when trying to submit. Below is his response. 

Hi Mike,

Process to register seems straightforward but it wouldn't let me submit when I'd finished - the following message was displayed:

"There seems to be an issue with our system at the moment, please try again later or alternativly contact us on info@barterproject.org"

Go back to the home page.

**Comment by TBSliver** [comment]
Yea thats been fixed since, so closing this now
