### ISSUE TITLE
RuntimeException When Redeeming Twice

### ISSUE THREAD

**Issue by cumpsty** [Pear-Trading/Android-Terminal#3]
When the same input ID number dialog is used for a second redeem, a RuntimeException is thrown.

**Comment by MichaelHallam** [comment]
Thats a pretty fundamental error. I assume it means that if a trader wants to log two sales from the same customer it throws a runtime exception?

and just to show you that I know what that is....
"An exception is an event, which occurs during the execution of a program, that disrupts the normal flow of the program's instructions. "  :)

**Comment by TBSliver** [comment]
Just checked, this is still the case:

input card as pear999 (the one im testing with)

redeem a point

input card as pear999 (without synching)

crash!

investigating now.

**Comment by MichaelHallam** [comment]
👍Michael

**Comment by TBSliver** [comment]
Hmm i think i fixed it by mistake, cant reproduce it. closing as solved unless it comes back again!
