### ISSUE TITLE
Just liked the regitstation page http://app.peartrade.org/api/ to the website at http://www.peartrade.org/

### ISSUE THREAD

**Issue by MichaelHallam** [Pear-Trading/Android-Terminal#4]
I have done this via the "get a card and start trading button" to make it easier for everyone working on this to quickly and easily track down and land on the registration page.

No one is currently using or finding their way to the website so I don't think spontaneous mass attempts at signing up will be a problem for the foreseeable future.

**Comment by TBSliver** [comment]
theres not been anyone able to register yet as things were a bit broken. I will get back to what needs fixing and editing shrotly, once ive got the entire thing actually pointing to itself correctly!
